version: "3"

services:
  dating-api:
    image: dating-api:latest
    container_name: dating-api 
    restart: always
    build: .
    ports:
      - "5000:5000"
    networks:
      my_network:
        ipv4_address: 172.16.238.10
    volumes:
      - ${ENV_VOL}:/env
      - ${LOG_VOL}:/log
    depends_on:
      - database

  database:
    image: mysql:latest
    ports:
     - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    user: mysql 
    volumes:
    - .data:/var/lib/mysql
    - ./dump:/docker-entrypoint-initdb.d
    networks:
      my_network:
        ipv4_address: ${DATABASE_HOST} 

  redis:
    image: redis:latest
    container_name: redis-dating-api 
    ports:
     - 6379:6379
    networks:
      my_network:
        ipv4_address: ${REDIS_HOST} 


networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24

